; Customer-TypeApps GUI WS list
; One URL per key/value line
; The first URL is selected by default if -WsBase is not passed

[WS]
primary=https://provision.wuibaille.fr
secondary=https://provision.wuibaille.fr
